"""
Django settings for sistema_vendas project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3q-&=6squefv$e)ikci3&wk6tb4mi_%9)39t%bvbn@8=3f9i#x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app_controle'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'app_controle.middleware.SessionExpireMiddleware',
]

ROOT_URLCONF = 'sistema_vendas.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sistema_vendas.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'u275872813_gen_estoque',
        'USER': 'u275872813_admin_estoque',
        'PASSWORD': 'GestaoEstoque25',
        'HOST': 'srv1061.hstgr.io',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# URL prefix for static files. Use a leading slash so paths are absolute.
STATIC_URL = '/static/'

# During development, also look for static files in the project-level `static/` folder
from pathlib import Path as _Path
STATICFILES_DIRS = [BASE_DIR / 'app_controle' / 'static']

# Optional: directory used by `collectstatic` in production
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================
# CONFIGURAÇÕES DE SESSÃO
# ============================================

# Sessão expira ao fechar o navegador
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Tempo de vida da sessão em segundos (opcional, caso queira limite de tempo também)
# SESSION_COOKIE_AGE = 3600  # 1 hora (descomente se quiser)

# Nome do cookie de sessão
SESSION_COOKIE_NAME = 'sessionid'

# Cookie de sessão acessível apenas via HTTP (segurança)
SESSION_COOKIE_HTTPONLY = True

# Cookie seguro apenas em HTTPS (descomente em produção)
# SESSION_COOKIE_SECURE = True

# Salvar sessão a cada requisição (mantém sessão ativa enquanto usar)
SESSION_SAVE_EVERY_REQUEST = True

# Backend de sessão (padrão é banco de dados)
SESSION_ENGINE = 'django.contrib.sessions.backends.db'