# Generated by Django 5.2.8 on 2026-02-07 04:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Cidade')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'db_table': 'cidade',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$', 'CPF inválido. Use o formato: 000.000.000-00')], verbose_name='CPF')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=120, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45, unique=True, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
                'verbose_name_plural': 'Formas de Pagamento',
                'db_table': 'forma_pagamento',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome Completo')),
                ('cpf_cnpj', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator('^(\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}|\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2})$', 'CPF/CNPJ inválido')], verbose_name='CPF/CNPJ')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'db_table': 'funcionario',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'Sigla deve ter 2 letras maiúsculas')], verbose_name='Sigla')),
                ('nome', models.CharField(max_length=45, verbose_name='Nome do Estado')),
            ],
            options={
                'verbose_name': 'UF',
                'verbose_name_plural': 'UFs',
                'db_table': 'uf',
                'ordering': ['sigla'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('email', models.EmailField(max_length=120, unique=True, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=255, verbose_name='Senha')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cep', models.CharField(blank=True, max_length=9, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{3}$', 'CEP inválido. Use o formato: 00000-000')], verbose_name='CEP')),
                ('principal', models.BooleanField(default=False, verbose_name='Endereço Principal')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enderecos', to='app_controle.cidade', verbose_name='Cidade')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='app_controle.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'db_table': 'endereco',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='app_controle.funcionario', verbose_name='Funcionário Responsável'),
        ),
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Loja')),
                ('cnpj', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator('^\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2}$', 'CNPJ inválido. Use o formato: 00.000.000/0000-00')], verbose_name='CNPJ')),
                ('senha', models.CharField(max_length=255, verbose_name='Senha')),
                ('telefone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\(\\d{2}\\)\\s?\\d{4,5}-?\\d{4}$', 'Telefone inválido. Use: (00) 00000-0000')], verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=120, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
                'db_table': 'loja',
                'indexes': [models.Index(fields=['cnpj', 'ativo'], name='idx_loja_cnpj_ativo')],
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('data_orcamento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Orçamento')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal')),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Desconto')),
                ('frete', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Frete')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('parcelamento', models.CharField(blank=True, max_length=45, verbose_name='Parcelamento')),
                ('observacao', models.TextField(blank=True, max_length=3000, verbose_name='Observação')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('CONVERTIDO', 'Convertido em Venda')], db_index=True, default='PENDENTE', max_length=20, verbose_name='Status')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='app_controle.cliente', verbose_name='Cliente')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='app_controle.formapagamento', verbose_name='Forma de Pagamento')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'db_table': 'orcamento',
                'ordering': ['-data_orcamento'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('descricao', models.CharField(max_length=120, verbose_name='Descrição')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('iof', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='IOF (%)')),
                ('controlar_estoque', models.BooleanField(default=True, verbose_name='Controlar Estoque')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'produto',
                'ordering': ['descricao'],
                'indexes': [models.Index(fields=['descricao'], name='idx_produto_descricao')],
            },
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app_controle.orcamento', verbose_name='Orçamento')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_orcamento', to='app_controle.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item de Orçamento',
                'verbose_name_plural': 'Itens de Orçamento',
                'db_table': 'item_orcamento',
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('quantidade_disponivel', models.IntegerField(default=0, verbose_name='Quantidade Disponível')),
                ('quantidade_minima', models.IntegerField(default=0, verbose_name='Estoque Mínimo')),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to='app_controle.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Estoques',
                'db_table': 'estoque',
            },
        ),
        migrations.AddField(
            model_name='cidade',
            name='uf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cidades', to='app_controle.uf', verbose_name='UF'),
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('data_venda', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Venda')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal')),
                ('desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Desconto')),
                ('frete', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Frete')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('parcelamento', models.CharField(blank=True, max_length=45, verbose_name='Parcelamento')),
                ('observacao', models.TextField(blank=True, max_length=3000, verbose_name='Observação')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='app_controle.cliente', verbose_name='Cliente')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='app_controle.formapagamento', verbose_name='Forma de Pagamento')),
                ('orcamento_origem', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venda_convertida', to='app_controle.orcamento', verbose_name='Orçamento de Origem')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'db_table': 'venda',
                'ordering': ['-data_venda'],
            },
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_venda', to='app_controle.produto', verbose_name='Produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app_controle.venda', verbose_name='Venda')),
            ],
            options={
                'verbose_name': 'Item de Venda',
                'verbose_name_plural': 'Itens de Venda',
                'db_table': 'item_venda',
            },
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['cpf'], name='idx_cliente_cpf'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nome'], name='idx_cliente_nome'),
        ),
        migrations.AddIndex(
            model_name='orcamento',
            index=models.Index(fields=['status', 'data_orcamento'], name='idx_orcamento_status_data'),
        ),
        migrations.AddIndex(
            model_name='cidade',
            index=models.Index(fields=['nome', 'uf'], name='idx_cidade_nome_uf'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['data_venda'], name='idx_venda_data'),
        ),
        migrations.AddIndex(
            model_name='venda',
            index=models.Index(fields=['cliente', 'data_venda'], name='idx_venda_cliente_data'),
        ),
    ]
