# Generated by Django 5.2.7 on 2025-11-21 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('idCIDADES', models.AutoField(primary_key=True, serialize=False)),
                ('NOME_CIDADE', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'db_table': 'CIDADES',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCLIENTE', models.AutoField(primary_key=True, serialize=False)),
                ('NOME_CLIENTE', models.CharField(max_length=120)),
                ('CPF', models.CharField(max_length=45)),
                ('TELEFONE', models.CharField(max_length=45)),
                ('EMAIL', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'CLIENTE',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('idFUNCIONARIO', models.AutoField(primary_key=True, serialize=False)),
                ('NOME_FUNCIONARIO', models.CharField(max_length=120)),
                ('CPF_CNPJ', models.CharField(max_length=45)),
                ('TELEFONE_FUNCIONARIO', models.CharField(max_length=45)),
                ('ATIVO', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'db_table': 'FUNCIONARIO',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('idPAGAMENTO', models.AutoField(primary_key=True, serialize=False)),
                ('TP_PAGAMENTO', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'db_table': 'PAGAMENTO',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('idPRODUTO', models.AutoField(primary_key=True, serialize=False)),
                ('DESCRICAO', models.CharField(max_length=120)),
                ('VLR_UNIT', models.CharField(max_length=45)),
                ('IOF', models.CharField(max_length=45)),
                ('DT_MOVIMENTADA', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'PRODUTO',
            },
        ),
        migrations.CreateModel(
            name='UF',
            fields=[
                ('idUF', models.AutoField(primary_key=True, serialize=False)),
                ('NOME_ESTADO', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'UF',
                'verbose_name_plural': 'UFs',
                'db_table': 'UF',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUSUARIO', models.AutoField(primary_key=True, serialize=False)),
                ('NOME_USUARIO', models.CharField(max_length=120)),
                ('EMAIL', models.CharField(max_length=120)),
                ('SENHA', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'USUARIO',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('idENDERECO', models.AutoField(primary_key=True, serialize=False)),
                ('LOGRADOURO', models.CharField(max_length=45)),
                ('NUMERO', models.IntegerField()),
                ('REFERENCIA', models.CharField(max_length=100)),
                ('CIDADES_idCIDADES', models.ForeignKey(db_column='CIDADES_idCIDADES', on_delete=django.db.models.deletion.PROTECT, to='app_controle.cidades')),
                ('CLIENTE_idCLIENTE', models.ForeignKey(db_column='CLIENTE_idCLIENTE', on_delete=django.db.models.deletion.PROTECT, to='app_controle.cliente')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'db_table': 'ENDERECO',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='FUNCIONARIO_idFUNCIONARIO',
            field=models.ForeignKey(db_column='FUNCIONARIO_idFUNCIONARIO', on_delete=django.db.models.deletion.PROTECT, to='app_controle.funcionario'),
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('idESTOQUE', models.AutoField(primary_key=True, serialize=False)),
                ('QTD_DISPONIVEL', models.IntegerField()),
                ('PRODUTO_idPRODUTO', models.ForeignKey(db_column='PRODUTO_idPRODUTO', on_delete=django.db.models.deletion.PROTECT, to='app_controle.produto')),
            ],
            options={
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Estoques',
                'db_table': 'ESTOQUE',
            },
        ),
        migrations.AddField(
            model_name='cidades',
            name='UF_idUF',
            field=models.ForeignKey(db_column='UF_idUF', on_delete=django.db.models.deletion.PROTECT, to='app_controle.uf'),
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('idVENDA', models.AutoField(primary_key=True, serialize=False)),
                ('PAGAMENTO_idPAGAMENTO', models.IntegerField()),
                ('QTD_VENDIDA', models.IntegerField()),
                ('DT_VENDA', models.DateTimeField()),
                ('VLR_TOTAL', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CLIENTE_idCLIENTE', models.ForeignKey(db_column='CLIENTE_idCLIENTE', on_delete=django.db.models.deletion.PROTECT, to='app_controle.cliente')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'db_table': 'VENDA',
            },
        ),
        migrations.CreateModel(
            name='EstoqueVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ESTOQUE_idESTOQUE', models.ForeignKey(db_column='ESTOQUE_idESTOQUE', on_delete=django.db.models.deletion.PROTECT, to='app_controle.estoque')),
                ('VENDA_idVENDA', models.ForeignKey(db_column='VENDA_idVENDA', on_delete=django.db.models.deletion.PROTECT, to='app_controle.venda')),
            ],
            options={
                'verbose_name': 'Estoque Venda',
                'verbose_name_plural': 'Estoque Vendas',
                'db_table': 'ESTOQUE_has_VENDA',
                'unique_together': {('ESTOQUE_idESTOQUE', 'VENDA_idVENDA')},
            },
        ),
    ]
