# Generated by Django 5.2.7 on 2025-12-03 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='DATA_NASCIMENTO',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='endereco',
            name='BAIRRO',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='endereco',
            name='CEP',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='EMAIL',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='FUNCIONARIO_idFUNCIONARIO',
            field=models.ForeignKey(blank=True, db_column='FUNCIONARIO_idFUNCIONARIO', null=True, on_delete=django.db.models.deletion.PROTECT, to='app_controle.funcionario'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='CLIENTE_idCLIENTE',
            field=models.ForeignKey(db_column='CLIENTE_idCLIENTE', on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='app_controle.cliente'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='LOGRADOURO',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='NUMERO',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='REFERENCIA',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
