# Generated by Django 5.2.8 on 2026-05-29 09:49

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^(\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}|\\d{2}\\.\\d{3}\\.\\d{3}/\\d{4}-\\d{2})$', 'CPF/CNPJ inválido. Use 000.000.000-00 (CPF) ou 00.000.000/0000-00 (CNPJ)')], verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='itemorcamento',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço Unitário'),
        ),
        migrations.AlterField(
            model_name='itemorcamento',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='itemorcamento',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço Unitário'),
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Desconto'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='frete',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Frete'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='iof',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='IOF (%)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Preço Unitário'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Desconto'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='frete',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Frete'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total'),
        ),
    ]
