# Generated by Django 5.2.7 on 2025-12-05 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle', '0002_cliente_data_nascimento_endereco_bairro_endereco_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='DESCONTO',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venda',
            name='VLR_SUBTOTAL',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venda',
            name='CLIENTE_idCLIENTE',
            field=models.ForeignKey(db_column='CLIENTE_idCLIENTE', on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='app_controle.cliente'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='DT_VENDA',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='PAGAMENTO_idPAGAMENTO',
            field=models.ForeignKey(db_column='PAGAMENTO_idPAGAMENTO', on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='app_controle.pagamento'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='QTD_VENDIDA',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('idITEM_VENDA', models.AutoField(primary_key=True, serialize=False)),
                ('QUANTIDADE', models.IntegerField()),
                ('VLR_UNITARIO', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VLR_TOTAL', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PRODUTO_idPRODUTO', models.ForeignKey(db_column='PRODUTO_idPRODUTO', on_delete=django.db.models.deletion.PROTECT, to='app_controle.produto')),
                ('VENDA_idVENDA', models.ForeignKey(db_column='VENDA_idVENDA', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app_controle.venda')),
            ],
            options={
                'verbose_name': 'Item de Venda',
                'verbose_name_plural': 'Itens de Venda',
                'db_table': 'ITEM_VENDA',
            },
        ),
    ]
