# Generated by Django 5.2.7 on 2026-01-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle', '0003_venda_desconto_venda_vlr_subtotal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('idLOJA', models.AutoField(primary_key=True, serialize=False)),
                ('NOME_LOJA', models.CharField(max_length=200, verbose_name='Nome da Loja')),
                ('CNPJ', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('SENHA', models.CharField(max_length=255, verbose_name='Senha')),
                ('TELEFONE', models.CharField(blank=True, max_length=45, null=True)),
                ('EMAIL', models.EmailField(blank=True, max_length=120, null=True)),
                ('ENDERECO', models.CharField(blank=True, max_length=255, null=True)),
                ('DATA_CADASTRO', models.DateTimeField(auto_now_add=True)),
                ('ATIVO', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
                'db_table': 'LOJA',
            },
        ),
    ]
