# Generated by Django 5.2.8 on 2026-01-25 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle', '0004_loja'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('idORCAMENTO', models.AutoField(primary_key=True, serialize=False)),
                ('QTD_ITENS', models.IntegerField(default=0)),
                ('DT_ORCAMENTO', models.DateTimeField(auto_now_add=True)),
                ('VLR_SUBTOTAL', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('DESCONTO', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('VLR_TOTAL', models.DecimalField(decimal_places=2, max_digits=10)),
                ('STATUS', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('CONVERTIDO', 'Convertido em Venda')], default='PENDENTE', max_length=20)),
                ('CLIENTE_idCLIENTE', models.ForeignKey(db_column='CLIENTE_idCLIENTE', on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='app_controle.cliente')),
                ('PAGAMENTO_idPAGAMENTO', models.ForeignKey(db_column='PAGAMENTO_idPAGAMENTO', on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='app_controle.pagamento')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'db_table': 'ORCAMENTO',
            },
        ),
    ]
