# Generated by Django 5.2.8 on 2026-01-25 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle', '0005_orcamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('idITEM_ORCAMENTO', models.AutoField(primary_key=True, serialize=False)),
                ('QUANTIDADE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VLR_UNITARIO', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VLR_TOTAL', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ORCAMENTO_idORCAMENTO', models.ForeignKey(db_column='ORCAMENTO_idORCAMENTO', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app_controle.orcamento')),
                ('PRODUTO_idPRODUTO', models.ForeignKey(db_column='PRODUTO_idPRODUTO', on_delete=django.db.models.deletion.PROTECT, related_name='itens_orcamento', to='app_controle.produto')),
            ],
            options={
                'verbose_name': 'Item de Orçamento',
                'verbose_name_plural': 'Itens de Orçamento',
                'db_table': 'ITEM_ORCAMENTO',
            },
        ),
    ]
