# Generated by Django 5.2.8 on 2026-02-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle', '0006_itemorcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='VLR_FRETE',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venda',
            name='VLR_FRETE',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
