# Generated by Django 5.2.8 on 2026-02-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle', '0007_orcamento_vlr_frete_venda_vlr_frete'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='OBSERVACAO',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='OBSERVACAO',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
