# Generated by Django 5.2.8 on 2026-02-04 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle', '0008_orcamento_observacao_venda_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='DT_ORCAMENTO',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='venda',
            name='DT_VENDA',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
