# Generated by Django 5.2.8 on 2026-02-04 17:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle', '0009_alter_orcamento_dt_orcamento_alter_venda_dt_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='DT_ORCAMENTO',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='venda',
            name='DT_VENDA',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
