# Generated by Django 5.2.8 on 2026-02-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle', '0010_alter_orcamento_dt_orcamento_alter_venda_dt_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='TRACK_STOCK',
            field=models.BooleanField(default=True),
        ),
    ]
