# Generated by Django 5.2.8 on 2026-02-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle', '0011_produto_track_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='PARCELAMENTO',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='PARCELAMENTO',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
