# Generated by Django 5.2.8 on 2026-02-04 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle', '0012_orcamento_parcelamento_venda_parcelamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='ORCAMENTO_ORIGEM',
            field=models.ForeignKey(blank=True, db_column='ORCAMENTO_idORCAMENTO', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas_convertidas', to='app_controle.orcamento'),
        ),
    ]
